Document: haftian
Title: Debian haftian Manual
Author: <insert document author here>
Abstract: This manual describes what haftian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/haftian/haftian.sgml.gz

Format: postscript
Files: /usr/share/doc/haftian/haftian.ps.gz

Format: text
Files: /usr/share/doc/haftian/haftian.text.gz

Format: HTML
Index: /usr/share/doc/haftian/html/index.html
Files: /usr/share/doc/haftian/html/*.html
